### ISSUE TITLE
[BUG] Can't filter by tags

### ISSUE THREAD

**Issue by Morcegolas** [Michael-128/qBitControl#1]
**Describe the bug**
Can't filter by tags, all the others work, this one always show an amply list. 

**Smartphone (please complete the following information):**
 - Device: iPhone14 Pro Max
 - OS: iOS17.2.1
 - Browser safari

**Comment by Michael-128** [comment]
Thank you for reporting the bug. I'll fix that as soon as I can.

**Comment by Michael-128** [comment]
The issue has been fixed. You can get the latest version here: https://github.com/Michael-128/qBitControl/releases/tag/CI

**Comment by Morcegolas** [comment]
You do not have to be so fast, I just reported so that you know. 
Thank.
