### ISSUE TITLE
[Feature] Push app to App Store

### ISSUE THREAD

**Issue by rodrigogonegit** [Michael-128/qBitControl#13]
Hey, would it be viable for you to push the app to the App Store?

**Comment by Michael-128** [comment]
Unfortunately, I can't publish the app on the App Store due to Apple's guidelines. I have already tried, but it was rejected.

**Comment by rodrigogonegit** [comment]
Thanks for the quick reply :). Love the UI of the app btw.

**Comment by rodrigogonegit** [comment]
Sorry for reviving this, but would publishing on AltStore work?

**Comment by Michael-128** [comment]
No problem! If you mean AltStore PAL - it is coming very soon. The app will be available to download for a small donation to help me cover the cost of apple developer fee. Feel free to ask any questions :)

**Comment by rodrigogonegit** [comment]
Sounds good to me. Keep us posted :)

**Comment by Michael-128** [comment]
It took a bit longer than I've anticipated, but qBitControl is finally on AltStore PAL! If you are interested, you can check it out in the recommended sources list, but make sure you update AltStore PAL to the newest version first.

**Comment by rodrigogonegit** [comment]
Hey @Michael-128, thanks a lot for going through the trouble of publishing it :). However, I'm not the biggest fan of subscriptions (as you probably know, self hosting enthusiasts rarely are). As such, I would be more than happy to pay for the app for a one time purchase, like the good ol' days.

I completely understand if that's not something you're interested in. Thank you again!

**Comment by Michael-128** [comment]
No problem! I thought about making one-time payment, but as of now AltStore PAL doesn't support that.
