### ISSUE TITLE
[BUG] Category does not properly sets save path

### ISSUE THREAD

**Issue by 68kdmd** [Michael-128/qBitControl#14]
**Describe the bug**
When a torrent file is added through the app with a pre-defined category, the save path is not properly defined.

**To Reproduce**
1. Add Task
2. Open a torrent file
3. choose a pre-defined category (with corresponding save path already set)
4. save path does not reflect the category directory, and the data is saved in a torrent root folder

**Expected behavior**
torrent is saved in corresponding directory associated with the category

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 17.6
 - Browser Safari
 - qBitControl CI

**Additional context**

**Comment by Michael-128** [comment]
Thanks for reporting the bug! I will look into it.
