### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by ori2015** [Michael-128/qBitControl#18]
![photo_2024-07-25_17-47-01](https://github.com/user-attachments/assets/277d0b56-30b3-4807-be27-7126a7b41eb5)
![photo_2024-07-25_17-47-04](https://github.com/user-attachments/assets/f8caeee2-3ab5-4875-8b64-45fce8435839)
![photo_2024-07-25_17-47-08](https://github.com/user-attachments/assets/e7286e10-73a7-45b5-bed9-85b25beda84d)

**Smartphone (please complete the following information):**
 - Device:iphone 12 pro max
 - OS: 17.5.1

I tried to download several versions I get the same error if I enter the address through the browser it does work so the address is correct

**Additional context**

**Comment by Michael-128** [comment]
Have you disabled 'Check connection' before adding the server?

**Comment by ori2015** [comment]
> Have you disabled 'Check connection' before adding the server?

Yes because it was the only way to go to the next level but it doesn't work there either

**Comment by Michael-128** [comment]
I see in your second screenshot that the username and password fields are empty. Credentials also have to be correct to connect with qBittorrent.

**Comment by ori2015** [comment]
![IMG_3793](https://github.com/user-attachments/assets/3f6f8919-d4c4-40a0-9332-cb3346dd5293)

It still doesn't work and the username and password are correct in the browser

**Comment by Michael-128** [comment]
Just to confirm you can log into qBittorrent from the browser on your iPhone using the credentials? Are you using qBittorrent without a password?

**Comment by ori2015** [comment]
Yes, through the browser it works and I tried both with and without a password

**Comment by Michael-128** [comment]
I just noticed, are you using a public ip? If so I think it's the reason why you can't connect. In such case I'll have to look info if such connections can even be made and update the app.

**Comment by ori2015** [comment]
Yes, it's through an external address, I did port forwarding, why does it work through the browser and not through the app?

**Comment by Michael-128** [comment]
Okay, it's not an issue on your end. The app doesn't allow HTTP connections over the internet by default. By the way are you using the AltStore PAL version or sideloaded from GitHub?

**Comment by ori2015** [comment]
sideloaded From git

But just so you know in this app https://github.com/Jbcbro/qBitRemote-Public it does work so maybe you can take away the remote connection part, just the design of your app is better so I want to use it

**Comment by Michael-128** [comment]
I've made a change so that HTTP connections over the internet can be made, you can download it [here](https://github.com/Michael-128/qBitControl/releases/tag/CI). Please let me know if it works.

Just be aware that HTTP connections are generally insecure as anyone can see your server requests - they are unencrypted. Using a VPN to connect to the network your server is in or getting a cheap domain with a SSL certificate would be a lot safer.

**Comment by ori2015** [comment]
Wowwww thank you very much it works 
and don't worry I connect via VPN

**Comment by Michael-128** [comment]
That's great! I hope you enjoy using the app :)

**Comment by 68kdmd** [comment]
Safer way would be to just use tailscale (with subnet routing if needed)? Works perfectly in my case.
