### ISSUE TITLE
[BUG] Availability is displaying incorrect percentage

### ISSUE THREAD

**Issue by BitlessByte0** [Michael-128/qBitControl#21]
**Describe the bug**
On the torrent screen, the availability is showing the incorrect percentage by a factor of 100. 

**To Reproduce**
1. Add torrent 
2. Go to torrent screen
3. Observe availability percentage 

**Expected behavior**
If I have a torrent with an availability of 1 (according to qBittorrent) then the app displays "1.0%" this should be "100%", or, simply "1.0" without the percentage sign. 

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro Max
 - OS: iOS 17.6.1

**Comment by Michael-128** [comment]
Thanks for reporting the bug! I will fix it soon

**Comment by Michael-128** [comment]
The availability percentage should be displayed correctly now. You can get the newest release [here](https://github.com/Michael-128/qBitControl/releases/tag/CI).
