### ISSUE TITLE
[BUG] Unable to see any torrent in the task view

### ISSUE THREAD

**Issue by LucaTomei** [Michael-128/qBitControl#22]
**Describe the bug**
The problem is that I'm unable to see any torrent in the task view. If I add a torrent everything is ok and also statistics are shown.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhon 13 Pro
 - OS: iOS 17.5.1

**Additional context**
I've also "sniffed" the api used by the app via HTTPS to my server and the api "torrents/list" return the correct json with the list of all the torrents that I have.

**Comment by Michael-128** [comment]
If I understand correctly, torrents are only showing up after you add a new torrent?

**Comment by LucaTomei** [comment]
Hi Michael,
No, if I add a torrent or a magnet link I can see it downloading on safari but not on the application.

**Comment by Michael-128** [comment]
Did you make sure you don't have any category/filter selected? That could prevent you from seeing your torrents. You can do that if you click on the icon in the top right corner of the screen - in 'Categories' section select 'None' and in 'Filter By' section select 'All'.

**Comment by Michael-128** [comment]
There was a bug that prevented torrents from being displayed when connecting to older qBittorrent versions. You can get the latest version [here](https://github.com/Michael-128/qBitControl/releases/tag/CI). Let me know if it works for you.

**Comment by Michael-128** [comment]
#27
