### ISSUE TITLE
[BUG] ipa is 1.1

### ISSUE THREAD

**Issue by SiNaPsEr0x** [Michael-128/qBitControl#23]
please fix ipa release becouse is 1.1

**Comment by Michael-128** [comment]
I know, I've forgot to set the version before the release. I will fix that

**Comment by SiNaPsEr0x** [comment]
you fix it?

**Comment by Michael-128** [comment]
The new 1.2.1 release has an appropriate version and build number. You can get the newest version [here](https://github.com/Michael-128/qBitControl/releases/tag/CI).
