### ISSUE TITLE
[BUG] No torrents listed

### ISSUE THREAD

**Issue by Al-Azraq** [Michael-128/qBitControl#27]
Hello,

No torrent is listed in the app despite not having any filter.

**To Reproduce**
1. Go to '.Tasks'
2. Click on 'filters'
3. Select ‘all’

Check the list of torrents currently added to Qbittorrent previously.

![image](https://github.com/user-attachments/assets/f0cecf8a-9f51-4747-99f6-48318971de59)

![image](https://github.com/user-attachments/assets/8d2f3857-dfd0-472f-906d-5b9c770b71c9)

 - Device: iPhone 14 Pro Max
 - OS: iOS 17.6.1
 - Qbittorrent Version: 4.2.5 (Raspberry Pi)

**Comment by Al-Azraq** [comment]
Thanks a lot dude, but I don’t even know how to sideload. I just use the AltStore PAL version.

Hopefully someone else can try.

**Comment by Michael-128** [comment]
I see, I will try to release the new version on AltStore PAL soon. You could also update qBittorrent to the lastest version if you want and the torrents should be displayed properly.

**Comment by Al-Azraq** [comment]
Sounds great! Thanks a lot!

I will try to update qBittorrent later today.

**Comment by Al-Azraq** [comment]
Thanks man! Just yesterday I’ve got my way around sideloady and installed the prerelease version which works great with qBittorrent 4.2.5.

**Comment by Michael-128** [comment]
That's great!
