### ISSUE TITLE
[Feature] Edit Server

### ISSUE THREAD

**Issue by JshGrn** [Michael-128/qBitControl#28]
**Is your feature request related to a problem? Please describe.**
Yes, I need to change server settings but can't edit the server (or I don't see how)

**Describe the solution you'd like**
To be able to hold down on the server name and go back to edit settings

**Describe alternatives you've considered**
Deleting it and re-adding it

**Additional context**
I don't want to keep deleting and re-adding when I change a simple setting :)

**Comment by Michael-128** [comment]
I will add this 👍

**Comment by JshGrn** [comment]
Awesome - thanks, looking forward to it!

**Comment by Michael-128** [comment]
New update is already available on AltStore PAL and on [GitHub](https://github.com/Michael-128/qBitControl/releases/tag/1.2.2).
