### ISSUE TITLE
[BUG] category save path redundancy 

### ISSUE THREAD

**Issue by 68kdmd** [Michael-128/qBitControl#29]
I’m on 1.21, and the category save path redundancy still persists. 

I’m currently using subcategories, and when it’s selected (eg /Movies/new) in the app Add-category, the ‘save path’ value correctly shows. However, the file gets actually saved under ‘/Movies/new/Movies/new’  

This issue is not specific to subcategories, as it displayed the same issue (Movies/Movies) when using a regular Category option as well. 

To get around the issue, you can delete the auto-populated ‘save path’ string in the app upon selecting the category, for the time being.

**Comment by Michael-128** [comment]
Thanks for reporting the bug. What version of qBittorrent are you using?

**Comment by 68kdmd** [comment]
The issue was seen in both 4.6.5 and 4.6.6

**Comment by Michael-128** [comment]
It's strange, because I also use 4.6.5 and never had this bug. It seems that subcategories are not available in the WebUI. What operating system do you use for your qBittorrent instance?

**Comment by 68kdmd** [comment]
That’s interesting. I just checked again and the issue is still present on 1.21. Qbit 4.6.6 docker. 

Issue present on both category and subcategory.

**Comment by 68kdmd** [comment]
Do you use the ‘automatic torrent management’ feature? I am. So, when creating a category in qbit webui, I defined ‘Movies’ as a save path as well.

**Comment by Michael-128** [comment]
I've never used automatic torrent management before, I will look into it and see if it causes this issue

**Comment by Michael-128** [comment]
I enabled automatic torrent management on my test instance of qBittorrent. When I add a torrent with category like on the screenshot above it's indeed saved in /downloads/Movies/Movies. I'll try to fix it

**Comment by 68kdmd** [comment]
I see. The TMM is pretty useful for quickly moving/organizing torrents data, and I use qbit_manage to automate TMM on for all my torrents. It gave me a frustrating experience initially (mass file copying/moving across storage volumes) but it was my fault because I was using incomplete save folder that was on a separate device.

**Comment by Michael-128** [comment]
I've disabled path auto-complete when automatic torrent management is enabled, since it seems that providing the full path is unnecessary. If you fill in the path field, the path will be appended to the default path for the category like it happened before. You can get the latest version [here](https://github.com/Michael-128/qBitControl/releases/tag/CI). Let me know if it works

**Comment by 68kdmd** [comment]
It’s working perfectly now with an option to add additional path manually. Thanks!
