### ISSUE TITLE
[BUG] statistics error

### ISSUE THREAD

**Issue by Alex92748** [Michael-128/qBitControl#30]
**Describe the bug**
All my statistics is zero, but they show normally on WebUI.

**Screenshots**

qbit-server:qbittorrent-nox 4.5.2
![IMG_6AE67EB9285B-1](https://github.com/user-attachments/assets/9de1b270-f3ad-4d46-ad5a-53dda2b0085c)
<img width="835" alt="截屏2024-09-17 20 53 19" src="https://github.com/user-attachments/assets/52f10159-bef3-4b0c-a89e-25864b43ae65">

**Smartphone (please complete the following information):**
 - Device: iPhone 15
 - OS: iOS 18.0

**Comment by 68kdmd** [comment]
![IMG_9377](https://github.com/user-attachments/assets/9356af75-564e-49e8-93f7-74897bf1f2a6)
![IMG_9379](https://github.com/user-attachments/assets/2f5b98a8-0bf9-4f64-a2ff-5f83a636d099)

The stat function has been working solid since the first introduction for me. 

Can you try starting your torrents and see if the stats update? You have no traffic according to your screenshot.

**Comment by Alex92748** [comment]
![IMG_5761C90CD7BC-1](https://github.com/user-attachments/assets/6d22e2be-5867-4104-b7f1-4cc7cae01a82)

**Comment by 68kdmd** [comment]
What version is your qBitControl?

Also, installation method? Sideloaded or AltStore PAL?

What is the locale of your iOS device?
![IMG_9383](https://github.com/user-attachments/assets/003ce927-3ee4-482e-8a16-fe736146f0b2)

**Comment by Alex92748** [comment]
qBitContro l1.2.1
installation Xcode
locale is china mainland
the reason for speed limit is that ISP will ban me if upload is too much😂

**Comment by 68kdmd** [comment]
I see. Have you tried it with sideloading (AltStore) and/or changing the locale for the testing purposes? If we narrow down the issue, it’d  be easier for Michael to fix it.

**Comment by Alex92748** [comment]
I have done sideloading by Altstore, changed to US and language EN. still error

**Comment by Alex92748** [comment]
I find problem is qbittorrent-nox 4.5.2. When I changed to qBittorrent 4.6.7, it fixed.

**Comment by 68kdmd** [comment]
Ah that’s  great. Nox must be using different api variables.

**Comment by Alex92748** [comment]
And qbittorrent-nox v4.6.7 works normally, so it's just because version too old🤣
