### ISSUE TITLE
[Feature] Quality of life enhancements for multiple server support

### ISSUE THREAD

**Issue by aptkingston** [Michael-128/qBitControl#4]
These are a few small suggestions for improvements after using the new multiple server support feature. I felt it was more appropriate to compile these into a single issue rather than create multiple for such small suggestions.

**Describe the solution you'd like**
- The server URL field has spellcheck enabled, which makes it difficult to type a URL as it keeps autocorrecting. It might be a good idea to disable spellcheck here.
- There's no validation for any of the server detail fields. This doesn't cause any issues, but it does let you do things like create a completely empty server with no name, that shows as an empty option in the server list. Making at least the name and URL required might help.
- Selecting an invalid server (e.g. one with no URL, or an invalid URL) does not show an error message until you click on it twice (maybe just a long timeout?). It also does not show as selected - the checkmark remains on the last valid server, but the navigation tab bar hides as if the new invalid server has been selected.

Great work on this new feature - it works perfectly and these are just some minor things I noticed when using it.

**Comment by Michael-128** [comment]
Thank you for providing valuable feedback and suggestions regarding the multiple server support feature!

I have implemented the following changes:
  - Disabled autocorretion for all fields in 'Add Server' view.
  - Added input validation for URL (URL has to include protocol).
  - Added server validation by checking connection (can be disabled).
  - Improved the process of changing active server
      - Now active server doesn't change if connection to selected sever couldn't be made.
      - Checkmark is not shown if qBitControl is not connected to any servers.
