### ISSUE TITLE
[Feature] First / Last pieces first

### ISSUE THREAD

**Issue by Drun555** [Michael-128/qBitControl#40]
This checkmark is essential in case you want to properly watch a video while downloading - without it, as I understand, after changing time position the videoplayer will be forced to re-cache entire video “before”. 

Not so sure about mechanism that works under the hood of players, but typically downloading F/L pieces first makes watching far more stable.

**Comment by Michael-128** [comment]
I will add this 👍

**Comment by Drun555** [comment]
That's great to hear, thank you!
