### ISSUE TITLE
[Feature] Queue/Priority Management

### ISSUE THREAD

**Issue by Nixon506E** [Michael-128/qBitControl#5]
**Is your feature request related to a problem? Please describe.**
It would be great to be able to move downloads up and down the queue.

**Describe the solution you'd like**
I would hope to see buttons for moving up one, down one, to top, to bottom. As well a details list item for the priority number in the queue and a way to sort the task list by priority.

**Describe alternatives you've considered**
The menu item showing the priority number could also be used to change the priority number more specifically; subsequently bumping the torrents at that priority and lower down one.

**Comment by Michael-128** [comment]
Thanks for the suggestion! I'll consider adding something like that.

**Comment by Michael-128** [comment]
I've added queue management, you can download the latest version of the app [here](https://github.com/Michael-128/qBitControl/releases/tag/CI). Let me know if it fits your needs.

**Comment by Nixon506E** [comment]
That was some quick work, thanks!

One suggestion I would make is that tasks without a priority are currently showing as 0 which sorts to the top where they should probably sort to the bottom below tasks with an actual priority.

**Comment by Michael-128** [comment]
I'm sorry for the late response. The tasks with priority higher than zero should always be on top if the list is sorted by priority either ascending or descending. Are you sure you are sorting by priority?
