### ISSUE TITLE
[Feature] Sequential download option upon adding a torrent or at least in a torrent's options

### ISSUE THREAD

**Issue by blahdy** [Michael-128/qBitControl#7]
A rather essential feature, even transmission got this implemented after years of opposition.

**Comment by Michael-128** [comment]
I've added the option to toggle sequential download on and off in the torrent details, it's also available when adding new torrents. You can check it out here: https://github.com/Michael-128/qBitControl/releases/tag/CI

**Comment by blahdy** [comment]
> I've added the option to toggle sequential download on and off in the torrent details, it's also available when adding new torrents. You can check it out here: https://github.com/Michael-128/qBitControl/releases/tag/CI

thanks mate!

**Comment by blahdy** [comment]
since we're talking features, perhaps you'd like to use a more eye pleasing app icon from our repo?
https://github.com/vit9696/qBittorrent/raw/master/graphics/dist/mac/qbittorrent_mac.icns

**Comment by Michael-128** [comment]
Thanks for the suggestion. I'll stay with the current one for now.
