### ISSUE TITLE
[BUG] Pause doesn't work

### ISSUE THREAD

**Issue by blahdy** [Michael-128/qBitControl#9]
**Describe the bug**
Pause doesn't work, nor can a paused torrent be resumed.

**Smartphone (please complete the following information):**
 - Device: [ios 17]
qbittorrent is from the master branch

**Comment by Michael-128** [comment]
I can't reproduce the bug. Could you give me more details?

**Comment by Michael-128** [comment]
I will close the issue as there is no further activity.
